### ISSUE TITLE
Example for evaluation

### ISSUE THREAD

**Issue by okanduzyel** [DIAGNijmegen/picai_eval#2]
Hi, 

I try to understand behind of the idea of the code of pica_eval. Could you give me an small example how to evaluate dataset with terminal codes? Just some codes preparing or starting evaluation which are using on your machine, that's enough for me. 

I couldn't start the evaluation with that code:

`python -m picai_eval --input path/to/detection_maps --labels path/to/annotations`

**Comment by okanduzyel** [comment]
```
Last login: Tue May 31 09:45:46 on ttys000
(base) okanduzyel@Okan-MacBook-Pro ~ % cd /Users/okanduzyel/PycharmProjects/picai_eval
(base) okanduzyel@Okan-MacBook-Pro picai_eval % python -m picai_eval --input path/to/detection_maps --labels path/to/annotations
If you have questions or suggestions, feel free to open an issue at https://github.com/DIAGNijmegen/picai_eval


    PICAI Evaluation
    Model predictions path: path/to/detection_maps
    Labels path: path/to/detection_maps
    Output Metrics Path: path/to/detection_maps/metrics.json

Traceback (most recent call last):
  File "/Users/okanduzyel/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/okanduzyel/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/picai_eval/__main__.py", line 52, in <module>
    assert os.path.exists(args.input), f"Input folder does not exist at {args.input}!"
AssertionError: Input folder does not exist at path/to/detection_maps!

```

**Comment by okanduzyel** [comment]
I deleted the folder, picai_eval, and cloned again. Now it can work. I guess, previous time, I lived cloning problem. 

```
(base) okanduzyel@Okan-MacBook-Pro picai_eval % python -m picai_eval --input tests/test-maps/ --labels tests/test-maps/
If you have questions or suggestions, feel free to open an issue at https://github.com/DIAGNijmegen/picai_eval


    PICAI Evaluation
    Model predictions path: tests/test-maps/
    Labels path: tests/test-maps/
    Output Metrics Path: tests/test-maps/metrics.json

Found 22 files in the input directory, collecting detection_mapes with ['_detection_map.npz', '_detection_map.npy', '_detection_map.nii.gz', '_detection_map.nii', '_detection_map.mha', '_detection_map.mhd'] and labels with ['_label.npz', '_label.npy', '_label.nii.gz', '_label.nii', '_label.mha', '_label.mhd'].
Found prediction and label for 10 cases. Here are some examples:
['case-0', 'case-1', 'case-2', 'case-3', 'case-4']
Evaluating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 333.82it/s]
Metrics:
Metrics(auroc=75.00%, AP=27.78%, 10 cases, 10 lesions)
(base) okanduzyel@Okan-MacBook-Pro picai_eval % 
```

My last question, 

How can I train all data with that code? 

<img width="698" alt="Screen Shot 2022-05-31 at 13 04 35" src="https://user-images.githubusercontent.com/38145537/171149005-c8297e2b-ad6c-4fd8-8f6a-42558b11e87d.png">

**Comment by joeranbosma** [comment]
Hi @okanduzyel ,

From your error message “AssertionError: Input folder does not exist at path/to/detection_maps!” it seems your paths are wrong. You need to change the paths to the actual folders where you stored the detection maps and annotations. You can use absolute paths for this, is that makes it more clear. Such a path could look like “C://Users/you/detection_maps” on Windows, or “/Users/you/detection_maps” on Mac OS. 


Your final question us not clear to me. Could you elaborate on that?

**Comment by okanduzyel** [comment]
I would like to join PI-CAI compatition. Until now, I understand that picai_eval code trains the MRI data and gives us output metrics. 

How can I use it to train your 32gb dataset on that link below? 
https://zenodo.org/record/6517398

**Comment by joeranbosma** [comment]
Hi @okanduzyel,

Thanks for your clarification and welcome to the PI-CAI Challenge! The picai_eval repository only handles the evaluation of the detection maps from a trained AI model. The typical steps of preprocessing the data and training the AI model are not included here. 

We do have another repository that can help you to preprocess the PI-CAI dataset into the nnU-Net Raw Data Archive format, or into the nnDetection Raw Data Archive format. You can find this repository and documentation on this here: https://github.com/DIAGNijmegen/picai_prep

We are also actively working on a baseline solution to the PI-CAI challenge, which will handle model training. We expect to release this in about two weeks. When public, it will be here: https://github.com/DIAGNijmegen/picai_baseline

I hope this answers your questions.

**Comment by okanduzyel** [comment]
I am beginner of biomedical image processing, thus something are not clear for me everytime.

I can use that link in order to convert my dataset to nnU-Net Raw Data Archive. That main dataset has .mha files, so **MHA Archive → nnU-Net Raw Data Archive convertion** option looks okay for me?
https://github.com/DIAGNijmegen/picai_prep

After that conversation, how can I train this data and send the outputs to your chellange's leaderboard?

**Comment by joeranbosma** [comment]
Hi @okanduzyel, 
That’s correct! 

For training, we cannot help you at this point. Please check the announcements on pi-cai.grand-challenge.org for updates on this. Before we release the baseline solutions, you can check out frameworks like nnU-Net, nnDetection and MONAI. These frameworks will be used in the baselines, and are a great starting point for deep learning projects in general. 

Hope this helps,
Joeran
