### ISSUE TITLE
Multiple lesion candidates selection criteria

### ISSUE THREAD

**Issue by MMRohe** [DIAGNijmegen/picai_eval#24]
Hello,

I have a question about this criteria used for evaluation:

> multiple_lesion_candidates_selection_criteria: Used to account for [split-merge scenarios](https://www.nature.com/articles/s41598-020-64803-w/figures/1). When multiple lesion candidates have sufficient overlap with the ground-truth lesion, this condition determines which lesion candidate is selected as the true positive, and which lesion candidates are discarded or counted as false positives. Default: 'overlap' (which selects the lesion candidate with the highest degree of overlap).

It seems counter-intuitive to me to proceed that way by default. I would say that the selection criteria which makes the most sense to me is the score and it seems illogical to match prediction with lower score with GT if the overlaping is higher.

To explain why, if we consider a case where an algorithm makes one prediction at score 0.9 and one prediction with score 0.1 that both matches a single GT (and the second one has higher overlap), then the prediction at 0.9 will be "discarded" (or counted as FP depending on config) while the one at 0.1 will be considered true positive. This means that, when evaluating the algorithm at any operating point between 0.1 and 0.9, the evaluation will consider 1 false negative whereas in fact, a model functioning at such a operating point will actually have produced one single prediction which matches the GT and therefore is a true positive.

what do you think ?

**Comment by joeranbosma** [comment]
Dear @MMRohe,
Thanks for your question, it's always appreciated when someone takes a critical look at the methods! And apologies for the long time needed to answer.

I like to borrow this figure in these hit/miss considerations:
![image](https://github.com/user-attachments/assets/e8bd0767-cd41-4bc9-a667-966893a23a48)
**Figure**. Using object overlap to determine hit/miss, as demonstrated by six classes of the Nascimento nomenclature. (left-to-right): (1-1) true positive; (0-1) false positive; (1-0) false negative; (1-N) “merge” case, i.e. when the predicted segmentation has merged multiple objects from the ground-truth segmentation into a single object; (M-1) “split” case, i.e. when a single object from the ground-truth segmentation has been split into multiple objects by the predicted segmentation; (M-N) “split-merge” case, i.e. when multiple objects from the ground-truth segmentation are split and merged by the predicted segmentations. (Carass et al., 2020). 

For split-merge scenarios (1-N, M-1, M-N scenarios in the figure above), when selecting only one among multiple lesion candidates that correspond to a "hit" or >0.10 IoU overlap with the same ground-truth lesion, we can choose to emphasize localization (as done now, by considering the lesion candidate with the largest overlap irregardless of its likelihood score; meaning our selection criteria would not affect PR and FROC values across all possible thresholds in any **systematic** manner) or to emphasize risk stratification (by considering the lesion candidate with sufficient overlap and the highest likelihood score; meaning our selection criteria would definitively **improve** PR and FROC metrics across all possible thresholds). Selecting the latter would lead to a positive bias and push performance up across the board, whereas selecting the former would not affect our metrics in any systematic/biased manner. Of course, it's good to bear in mind, that split-merge scenarios arise in a really small fraction of cases, and that during deployment at real-time, all overlapping predictions for a given ground-truth lesion would always appear at once and it is up to the radiologist to exercise their judgement and make sense of it as they best see fit. 

This led to the two considerations for setting this as the default behaviour (and using it for evaluation in the PI-CAI challenge):
1. Using the lesion candidate with the largest overlap seemed to us to correspond most to the model's prediction of the lesion's malignancy. This was not chosen in a data driven manner, so this could reduce the model's performance.
2. In the default setup, a smaller lesion candidate with sufficient overlap is not counted as a false positive but rather discarded. If I recall correctly, doing this with the highest model prediction as selection criteria would cause a positive bias in the model's performance (overestimating its true performance).

In general, I don't think this lesion-level evaluation is perfect. In fact, I would love to see a more clinical-oriented lesion-level evaluation method, which takes into account the consequences for the patient management. However, such a lesion-level evaluation is tricky to design and execute, and was outside the scope of the PI-CAI challenge or `picai_eval`.

I hope this gives more insight into our considerations and answers your question. And of course, a different configuration can be used within the `picai_eval` framework if that better fits your needs!

Best,
Joeran

**Comment by MMRohe** [comment]
![splitmerge](https://github.com/user-attachments/assets/5eeb92a8-42b5-47fd-b837-1a6adf6f75e3)

Thanks a lot for your complete answer Joeran, I have drawn quickly the following "M-1 case" where I believe the "overlap" method to be a little bit biaising the results. 

In this case two prediction matches one ground truth object, the two prediction having score 0.1 and 0.95 and both of them overlaps with IoU > threshold but the overlap of the lesion with score 0.1 is higher. If I understand correctly, in this case the lesion with score 0.1 will be considered as true positive whereas the lesion with score 0.95 will be considered as false positive. And the FROC curve will count one FP up "until" threshold 0.1 and then 1 FP and 1 TP.

I feel like this is biaising the result of the FROC curve (and the AP curve too) because my understanding is that the different level of evaluation of the FROC curve should strictly corresponds to:
_"what would be the performance of a corresponding model that would operate at this specific threshold. Meaning sensitivity and number of false positive for the model if we discard all finding that are below the threshold at which we evaluate the model"_ 

And here, the 'evaluation' of the model at any threshold between 0.95 and 0.1 will not be completely accurate, because it will consider the 0.95 detection as a FP because it is overcome by a lower score prediction. So it does not really correspond to the evaluation of an actual model that would operate at such an operating point, because such a model will not produce the 0.1 finding.

It is not really a very important / major issue : as you said this case happens quite rarely and there are other considerations that support your choice. I was just curious about this choice and wanted to discuss the pro / cons of it, as we are also facing with this kind of problematic and we try to find what is the most logic and accurate methodology to evaluate our model.

Thanks again for your answer !

**Comment by joeranbosma** [comment]
Dear @MMRohe,

In the default `picai_eval` configuration and the PI-CAI challenge, the evaluation is slightly different. For the situation you draw, the evaluation will count one true positive at a threshold of 0.1, and nothing else, as the other lesion candidate is discarded. We chose not to count any false positives in this case, as we do not find that clinically meaningful in this configuration. As indicated, the choice for retaining the candidate with the largest overlap is to prevent bias in the evaluation, more than anything else.

As a side note: the lesion candidate with a score of 0.95 would still be taken as the case-level prediction.

I think it's difficult to improve the evaluation, without fine-tuning to the target application (e.g., biopsy planning, radiation therapy planning, go/no go choice for treatment/biopsy).

If you come up with a better strategy, I would love to hear it!

**Comment by MMRohe** [comment]
Yes indeed, it is really difficult to find an evaluation that is relevant for all application, and unfortunately I do not have one strategy that would be better in every case :)

I would say that for a pure "detection problem" taking the "risk stratification" approach seems more clinically meaningfull, as I find it weird that we "discard" a true positive in the evaluation of some operating points (in my example between 0.1 and 0.95) whereas we correctly consider it at the case-level prediction. I feel maybe more concerned about the bias to not evaluate correctly the model at higher threshold, than the bias to consider lower overlap lesion as TP.

But,  as you mentioned, the answer could definitely be different in other context such as biopsy planning and radiation therapy planning where accurate localization and segmentation of the lesion is more important.

Thanks again for this discussion !
