### ISSUE TITLE
Evaluate Individual Detection Maps with Python

### ISSUE THREAD

**Issue by riccardosamperna** [DIAGNijmegen/picai_eval#6]
The documentation is unclear for both _Evaluate Individual Detection Maps with Python_ and _Evaluating Individual Softmax Volumes using Python_, in both cases it is not specified that the evaluate() function is expecting an iterable for both y_pred and y_true.

**Comment by joeranbosma** [comment]
Hi @riccardosamperna,

Could you specify what is unclear in the case of _Evaluate Individual Detection Maps with Python_? Looking at the documentation, I think it should make it clear that the input is an iterable:

![39841818-AA39-4094-8C6A-EAFFAA690B44](https://user-images.githubusercontent.com/5995183/183242768-658a83bc-9e07-48a5-9042-3905cce4e58c.jpeg)

I'll remove the “Individual” from the title to prevent getting the wrong idea. As for evaluating softmax volumes, I'll add a note about the inputs. 

Kind regards,
Joeran

**Comment by riccardosamperna** [comment]
Hi @joeranbosma,

Thanks for your reply. I guess, indeed, the "Individual" in the title is the confusing part. There are a lot of other clues that points in the right direction (you should pass an iterable and not a single element) but reading "Evaluate Individual Detection Maps with Python", I thought, without thinking too much about it, I can pass one single detection map and get back a result. If you change "Evaluate Individual Detection Maps with Python" to "Evaluate Detection Maps with Python", it should remove the confusion. It is just a feedback to improve readability because I stumble in a dumb problem by passing a single element and not a list. 

An additional suggestion, I would add a check on what is passed to the evaluate function to make sure indeed that what is passed is an iterable and otherwise throw an error. At the moment, if you pass a single 3D numpy volume, evaluate() still tries to use it but it is just using it in the wrong way. It treats the 3D volume as an iterable of 2D slices. In my opinion, you should not allow this to happen. Again, just a suggestion for improving the codebase. 

I hope all the points I raised are helpful.

Best,
Riccardo

**Comment by joeranbosma** [comment]
Hi @riccardosamperna,

I've updated the documentation accordingly, thanks for the suggestion :)

As for checking the input shape, I'm afraid that isn't as easy. The codebase is aimed at 3D evaluation, but we would like to also support 2D evaluation of the same task. In that case, a 3D numpy array is a valid input, which cannot be disambiguated from a single 3D volume. Additionally, the input is restricted to be an iterator, not a numpy array. As such, we can't always know the full input shape in advance.

Thanks for your contribution, and hope this gives some context,
Joeran
